package com.app.billing.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ItemDto {
    private String id;
    
    private String itemCode; // Auto-generated by system, not required from user
    
    private String enCode; // EN Code for item identification
    
    @NotBlank(message = "Item name is required")
    private String itemName;
    
    private String description;
    private String category;
    private String unit;
    
    @NotNull(message = "Purchase price is required")
    private BigDecimal purchasePrice;
    
    @NotNull(message = "Selling price is required")
    private BigDecimal sellingPrice;
    
    private BigDecimal stockQuantity;
    private BigDecimal minStockLevel;
    private String hsnCode;
    private BigDecimal taxRate;
    private java.util.Map<String, Object> customFields; // Custom fields support
    private String lastUpdatedBy; // EmployeeCode of user who last updated
}

